//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCombo
    {
        public int IDChiTietComBo { get; set; }
        public Nullable<int> MaComBo { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
