//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNuocUong_HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietNuocUong_HoaDon()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaNuocUong { get; set; }
        public int IdChiTietNuocUong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual NuocUong NuocUong { get; set; }
    }
}
