//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime ThoiGianThanhToan { get; set; }
        public int MaBan { get; set; }
        public int MaNV { get; set; }
        public int IdChiTietMonAn { get; set; }
        public Nullable<int> IdChiTietNuocUong { get; set; }
        public Nullable<System.DateTime> ThoiGianDatHang { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual ChiTietMonAn ChiTietMonAn { get; set; }
        public virtual ChiTietNuocUong ChiTietNuocUong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
