//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;

    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietMonAn_HoaDon = new HashSet<ChiTietMonAn_HoaDon>();
            this.ComBo_PhanAn = new HashSet<ComBo_PhanAn>();
            this.MonAn_ChiTiet = new HashSet<MonAn_ChiTiet>();
            this.MonAn_ThanhPhanBanh = new HashSet<MonAn_ThanhPhanBanh>();
        }
    
        public int MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public decimal GiaTien { get; set; }
        public Nullable<int> IDLoaiBanh { get; set; }
        public Nullable<bool> X { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMonAn_HoaDon> ChiTietMonAn_HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComBo_PhanAn> ComBo_PhanAn { get; set; }
        public virtual LoaiBanh LoaiBanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn_ChiTiet> MonAn_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn_ThanhPhanBanh> MonAn_ThanhPhanBanh { get; set; }

 
    }
}
