//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietMonAns = new HashSet<ChiTietMonAn>();
            this.ComBo_PhanAn = new HashSet<ComBo_PhanAn>();
        }
    
        public int MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public int IdChiTietThanhPhan { get; set; }
        public int IdVoBanh { get; set; }
        public int IDKichThuocBanh { get; set; }
        public decimal GiaTien { get; set; }
        public string LoaiBanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMonAn> ChiTietMonAns { get; set; }
        public virtual ChiTietThanhPhanBanh ChiTietThanhPhanBanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComBo_PhanAn> ComBo_PhanAn { get; set; }
        public virtual KichThuocBanh KichThuocBanh { get; set; }
        public virtual VOBANH VOBANH { get; set; }
    }
}
