//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuocUong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NuocUong()
        {
            this.ChiTietNuocUong_HoaDon = new HashSet<ChiTietNuocUong_HoaDon>();
            this.ComBo_PhanUong = new HashSet<ComBo_PhanUong>();
        }
    
        public int MaNuocUong { get; set; }
        public string TenNuocUong { get; set; }
        public decimal GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNuocUong_HoaDon> ChiTietNuocUong_HoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComBo_PhanUong> ComBo_PhanUong { get; set; }
    }
}
