//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHangPIzza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHPHANBANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHPHANBANH()
        {
            this.ChiTietThanhPhanBanhs = new HashSet<ChiTietThanhPhanBanh>();
        }
    
        public int IdThanhPhan { get; set; }
        public string TenThanhPhan { get; set; }
        public decimal Giatien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThanhPhanBanh> ChiTietThanhPhanBanhs { get; set; }
    }
}
